### ISSUE TITLE
JSON with a key of "length" causes a problem

### ISSUE THREAD

**Issue by JohnMunsch** [NV/jsDump#3]
JSON requires quotes around keys so reserved words don't cause a problem. But I suspect there's an issue with jsDump's parsing because it returns "[ ]" for the following valid JSON:

{
    "width": 0,
    "length": 0
}

Change it slightly though:

{
    "width": 0,
    "length_": 0
}

and it parses and formats it just fine. My guess is that other reserved words might cause similar problems though I haven't tested that to make sure.

**Comment by JohnMunsch** [comment]
I'm confused. So it's OK that it can't handle some perfectly valid JSON?

**Comment by NV** [comment]
jsDump had a problem handling objects like `{length: 0}`. I fixed it in a317936e8aac834eddb51094043df49689d24008.
